<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.E9WDXMc' shared service.

return $this->privates['.service_locator.E9WDXMc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ActividadesController::delete' => ['privates', '.service_locator.zKsXS7g', 'get_ServiceLocator_ZKsXS7gService.php', true],
    'App\\Controller\\ActividadesController::edit' => ['privates', '.service_locator.zKsXS7g', 'get_ServiceLocator_ZKsXS7gService.php', true],
    'App\\Controller\\ActividadesController::index' => ['privates', '.service_locator.YWY88lj', 'get_ServiceLocator_YWY88ljService.php', true],
    'App\\Controller\\ActividadesController::show' => ['privates', '.service_locator.zKsXS7g', 'get_ServiceLocator_ZKsXS7gService.php', true],
    'App\\Controller\\CategoriaController::delete' => ['privates', '.service_locator.P9xNlEm', 'get_ServiceLocator_P9xNlEmService.php', true],
    'App\\Controller\\CategoriaController::edit' => ['privates', '.service_locator.P9xNlEm', 'get_ServiceLocator_P9xNlEmService.php', true],
    'App\\Controller\\CategoriaController::index' => ['privates', '.service_locator.eU0NbHH', 'get_ServiceLocator_EU0NbHHService.php', true],
    'App\\Controller\\CategoriaController::show' => ['privates', '.service_locator.P9xNlEm', 'get_ServiceLocator_P9xNlEmService.php', true],
    'App\\Controller\\ActividadesController:delete' => ['privates', '.service_locator.zKsXS7g', 'get_ServiceLocator_ZKsXS7gService.php', true],
    'App\\Controller\\ActividadesController:edit' => ['privates', '.service_locator.zKsXS7g', 'get_ServiceLocator_ZKsXS7gService.php', true],
    'App\\Controller\\ActividadesController:index' => ['privates', '.service_locator.YWY88lj', 'get_ServiceLocator_YWY88ljService.php', true],
    'App\\Controller\\ActividadesController:show' => ['privates', '.service_locator.zKsXS7g', 'get_ServiceLocator_ZKsXS7gService.php', true],
    'App\\Controller\\CategoriaController:delete' => ['privates', '.service_locator.P9xNlEm', 'get_ServiceLocator_P9xNlEmService.php', true],
    'App\\Controller\\CategoriaController:edit' => ['privates', '.service_locator.P9xNlEm', 'get_ServiceLocator_P9xNlEmService.php', true],
    'App\\Controller\\CategoriaController:index' => ['privates', '.service_locator.eU0NbHH', 'get_ServiceLocator_EU0NbHHService.php', true],
    'App\\Controller\\CategoriaController:show' => ['privates', '.service_locator.P9xNlEm', 'get_ServiceLocator_P9xNlEmService.php', true],
], [
    'App\\Controller\\ActividadesController::delete' => '?',
    'App\\Controller\\ActividadesController::edit' => '?',
    'App\\Controller\\ActividadesController::index' => '?',
    'App\\Controller\\ActividadesController::show' => '?',
    'App\\Controller\\CategoriaController::delete' => '?',
    'App\\Controller\\CategoriaController::edit' => '?',
    'App\\Controller\\CategoriaController::index' => '?',
    'App\\Controller\\CategoriaController::show' => '?',
    'App\\Controller\\ActividadesController:delete' => '?',
    'App\\Controller\\ActividadesController:edit' => '?',
    'App\\Controller\\ActividadesController:index' => '?',
    'App\\Controller\\ActividadesController:show' => '?',
    'App\\Controller\\CategoriaController:delete' => '?',
    'App\\Controller\\CategoriaController:edit' => '?',
    'App\\Controller\\CategoriaController:index' => '?',
    'App\\Controller\\CategoriaController:show' => '?',
]);
