<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.P9xNlEm' shared service.

return $this->privates['.service_locator.P9xNlEm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'categorium' => ['privates', '.errored..service_locator.P9xNlEm.App\\Entity\\Categoria', NULL, 'Cannot autowire service ".service_locator.P9xNlEm": it references class "App\\Entity\\Categoria" but no such service exists.'],
], [
    'categorium' => 'App\\Entity\\Categoria',
]);
