<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJGgN259\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJGgN259/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJGgN259.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJGgN259\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJGgN259\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JGgN259',
    'container.build_id' => '01cc76e1',
    'container.build_time' => 1573257253,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJGgN259');
