<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVq6QSOe\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVq6QSOe/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVq6QSOe.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVq6QSOe\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVq6QSOe\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Vq6QSOe',
    'container.build_id' => '31dbe750',
    'container.build_time' => 1568769779,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVq6QSOe');
